from __future__ import annotations

import re


_INDIA_STATE_ALIASES = {
    "andamanandnicobarislands": "AN",
    "an": "AN",
    "andhrapradesh": "AP",
    "ap": "AP",
    "arunachalpradesh": "AR",
    "ar": "AR",
    "assam": "AS",
    "as": "AS",
    "bihar": "BR",
    "br": "BR",
    "chandigarh": "CH",
    "ch": "CH",
    "chhattisgarh": "CG",
    "cg": "CG",
    "dadraandnagarhavelianddamananddiu": "DH",
    "dh": "DH",
    "delhi": "DL",
    "nctofdelhi": "DL",
    "dl": "DL",
    "goa": "GA",
    "ga": "GA",
    "gujarat": "GJ",
    "gj": "GJ",
    "haryana": "HR",
    "hr": "HR",
    "himachalpradesh": "HP",
    "hp": "HP",
    "jammuandkashmir": "JK",
    "jk": "JK",
    "jharkhand": "JH",
    "jh": "JH",
    "karnataka": "KA",
    "ka": "KA",
    "kerala": "KL",
    "kl": "KL",
    "ladakh": "LA",
    "la": "LA",
    "lakshadweep": "LD",
    "ld": "LD",
    "madhyapradesh": "MP",
    "mp": "MP",
    "maharashtra": "MH",
    "mh": "MH",
    "manipur": "MN",
    "mn": "MN",
    "meghalaya": "ML",
    "ml": "ML",
    "mizoram": "MZ",
    "mz": "MZ",
    "nagaland": "NL",
    "nl": "NL",
    "odisha": "OD",
    "orissa": "OD",
    "od": "OD",
    "puducherry": "PY",
    "pondicherry": "PY",
    "py": "PY",
    "punjab": "PB",
    "pb": "PB",
    "rajasthan": "RJ",
    "rj": "RJ",
    "sikkim": "SK",
    "sk": "SK",
    "tamilnadu": "TN",
    "tn": "TN",
    "telangana": "TS",
    "tg": "TS",
    "ts": "TS",
    "tripura": "TR",
    "tr": "TR",
    "uttarpradesh": "UP",
    "up": "UP",
    "uttarakhand": "UK",
    "ua": "UK",
    "uk": "UK",
    "westbengal": "WB",
    "wb": "WB",
}


def normalize_state_identifier(value: str | None) -> str:
    compact = re.sub(r"[^a-z0-9]+", "", (value or "").strip().lower())
    if not compact:
        return ""
    return _INDIA_STATE_ALIASES.get(compact, compact.upper())
