from datetime import time

from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import RequestFactory, SimpleTestCase, override_settings
from django.utils import timezone
from botocore.exceptions import NoCredentialsError
from rest_framework.response import Response

from helpers.cache_helpers import cached_api_response, invalidate_catalog_cache
from helpers.media_helpers import safe_media_url
from helpers.validators import validate_document_upload
from helpers.vendor_hours import get_vendor_availability


class VendorHoursTests(SimpleTestCase):
    class Vendor:
        is_open = True
        is_accepting_orders = True

        def __init__(self, opening_time, closing_time):
            self.opening_time = opening_time
            self.closing_time = closing_time

    def test_accepts_string_times(self):
        vendor = self.Vendor("09:00:00", "23:00:00")
        current_dt = timezone.datetime(2026, 5, 12, 12, 0, tzinfo=timezone.utc)

        is_open, message = get_vendor_availability(vendor, current_dt=current_dt)

        self.assertTrue(is_open)
        self.assertEqual(message, "Open now until 23:00")

    def test_accepts_time_objects(self):
        vendor = self.Vendor(time(9, 0), time(23, 0))
        current_dt = timezone.datetime(2026, 5, 12, 12, 0, tzinfo=timezone.utc)

        is_open, _message = get_vendor_availability(vendor, current_dt=current_dt)

        self.assertTrue(is_open)


class UploadValidatorTests(SimpleTestCase):
    def test_rejects_disallowed_document_extension(self):
        upload = SimpleUploadedFile(
            "payload.exe",
            b"not a document",
            content_type="application/octet-stream",
        )

        with self.assertRaises(ValueError):
            validate_document_upload(upload)


class SafeMediaUrlTests(SimpleTestCase):
    class MissingCredentialFile:
        @property
        def url(self):
            raise NoCredentialsError()

    def test_returns_default_when_storage_credentials_are_missing(self):
        url = safe_media_url(self.MissingCredentialFile())

        self.assertIsNone(url)

    @override_settings(USE_S3=True, PUBLIC_BACKEND_URL='https://api.example.test')
    def test_returns_stable_backend_url_for_s3_media(self):
        class S3File:
            name = 'vendor/logo.png'

            @property
            def url(self):
                raise AssertionError('S3 URL should be generated by the media endpoint.')

        self.assertRegex(
            safe_media_url(S3File()),
            r'^https://api\.example\.test/api/media/vendor/logo\.png/\?v=[0-9a-f]{12}$',
        )


@override_settings(
    CACHES={
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'backend-cache-helper-tests',
        }
    }
)
class CachedApiResponseTests(SimpleTestCase):
    def setUp(self):
        invalidate_catalog_cache()
        self.factory = RequestFactory()

    def test_reuses_cached_response_for_same_query(self):
        calls = {'count': 0}
        request = self.factory.get('/api/products/list/?category=bakery')

        def producer():
            calls['count'] += 1
            return Response({'count': calls['count']})

        first = cached_api_response(request, 'test:products', 30, producer)
        second = cached_api_response(request, 'test:products', 30, producer)

        self.assertEqual(first.data, {'count': 1})
        self.assertEqual(second.data, {'count': 1})
        self.assertEqual(second['X-Backend-Cache'], 'HIT')
        self.assertEqual(calls['count'], 1)

    def test_invalidate_catalog_cache_removes_cached_response(self):
        calls = {'count': 0}
        request = self.factory.get('/api/products/list/?category=bakery')

        def producer():
            calls['count'] += 1
            return Response({'count': calls['count']})

        cached_api_response(request, 'test:products', 30, producer)
        invalidate_catalog_cache()
        response = cached_api_response(request, 'test:products', 30, producer)

        self.assertEqual(response.data, {'count': 2})
