# Generated by Django 4.2.29 on 2026-04-05 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pickup_otp'),
        ('delivery', '0002_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('notified', 'Partners Notified'), ('accepted', 'Accepted'), ('failed', 'Failed - No Partners Found'), ('cancelled', 'Cancelled')], default='searching', max_length=20)),
                ('current_radius_km', models.FloatField(default=2.0)),
                ('max_radius_km', models.FloatField(default=20.0)),
                ('last_search_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_assignment', to='delivery.deliverypartner')),
                ('notified_partners', models.ManyToManyField(blank=True, related_name='notified_assignments', to='delivery.deliverypartner')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='orders.order')),
                ('rejected_partners', models.ManyToManyField(blank=True, related_name='rejected_assignments', to='delivery.deliverypartner')),
            ],
        ),
    ]
