# Generated by Django 4.2.29 on 2026-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching'), ('notified', 'Partners Notified'), ('accepted', 'Accepted'), ('timed_out', 'Timed Out - No Response'), ('failed', 'Failed - No Partners Found'), ('cancelled', 'Cancelled')], default='searching', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
