# Generated by Django 4.2.29 on 2026-05-24 16:00

from django.db import migrations, models
import helpers.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliverypartner_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('delivery_document')),
        ),
    ]
