# Generated by Django 4.2.29 on 2026-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_deliverypartner_id_proof'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['status', 'last_search_at'], name='assign_status_search_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['accepted_partner', 'status'], name='assign_partner_status_idx'),
        ),
    ]
