# Generated by Codex on 2026-06-03

from django.db import migrations, models
import helpers.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryassignment_assign_status_search_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='id_proof',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=helpers.upload_paths.DeliveryPartnerDocumentUploadPath('id_proof'),
            ),
        ),
    ]
