# Generated by Django 4.2.29 on 2026-10-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_deliverypartner_id_proof_document_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
