# Generated by Django 4.2.29 on 2026-04-05 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_vendorpayout_deliverypartnerpayout'),
        ('orders', '0003_order_pickup_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('invoice_type', models.CharField(choices=[('customer_receipt', 'Customer Receipt'), ('vendor_settlement', 'Vendor Settlement'), ('delivery_payout', 'Delivery Partner Payout')], max_length=25)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
