# Generated by Django 4.2.29 on 2026-05-24 16:00

from django.db import migrations, models
import helpers.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('invoice')),
        ),
    ]
