# Generated by Django 4.2.29 on 2026-04-28 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_adminauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermissionGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('dispatch.manage', 'Manage dispatch'), ('orders.manage', 'Manage orders'), ('catalog.manage', 'Manage catalog'), ('vendors.manage', 'Manage vendors'), ('customers.manage', 'Manage customers'), ('support.manage', 'Manage support'), ('finance.manage', 'Manage finance'), ('settings.manage', 'Manage platform settings'), ('audit.view', 'View audit logs'), ('notifications.manage', 'Manage notifications'), ('automation.manage', 'Manage scheduled tasks')], max_length=80)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_admin_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permission_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'permission'],
            },
        ),
        migrations.AddConstraint(
            model_name='adminpermissiongrant',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='unique_admin_permission_grant'),
        ),
    ]
