# Generated by Django 4.2.29 on 2026-05-24 16:00

from django.db import migrations, models
import helpers.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_currency_default_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('profile_image')),
        ),
    ]
