# Generated by Django 4.2.29 on 2026-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_invalidate_legacy_reset_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermissiongrant',
            name='permission',
            field=models.CharField(choices=[('dispatch.manage', 'Manage dispatch'), ('orders.manage', 'Manage orders'), ('catalog.manage', 'Manage catalog'), ('vendors.manage', 'Manage vendors'), ('customers.manage', 'Manage customers'), ('support.manage', 'Manage support'), ('finance.manage', 'Manage finance'), ('settings.manage', 'Manage platform settings'), ('audit.view', 'View audit logs'), ('notifications.manage', 'Manage notifications'), ('automation.manage', 'Manage scheduled tasks'), ('overview.view', 'View overview'), ('orders.view', 'View orders'), ('dispatch.view', 'View dispatch'), ('vendors.view', 'View vendors'), ('customers.view', 'View customers'), ('catalog.view', 'View catalog'), ('support.view', 'View support'), ('finance.view', 'View finance'), ('growth.view', 'View promotions'), ('growth.manage', 'Manage promotions'), ('notifications.view', 'View notifications'), ('automation.view', 'View jobs'), ('settings.view', 'View settings'), ('users.reset_password', 'Initiate password reset')], max_length=80),
        ),
    ]
