from .categories import CategoryListView
from .inventory import (
    ProductListView, FeaturedProductsView, ProductDetailView,
    VendorProductImagesView, VendorProductImageDetailView,
    VendorStockUpdateView, VendorLowStockView, AIImageGenerateView
)
from .reviews import ProductReviewViewSet
from .admin_views import (
    AdminCategoryListCreateView, AdminCategoryDetailView,
    AdminProductListCreateView, AdminProductDetailView, AdminProductViewSet
)
from products.views.catalog_views import (
    AdminCatalogProductDetailView,
    AdminCatalogProductImageDetailView,
    AdminCatalogProductImagesView,
    AdminCatalogProductGrantVendorView,
    AdminCatalogProductListCreateView,
    AdminCatalogProposalItemApproveView,
    AdminCatalogProposalItemRejectView,
    AdminCatalogProposalListView,
    AdminApproveVendorProductView,
    AdminPendingVendorProductListView,
    AdminRejectVendorProductView,
    VendorAvailableCatalogProductsView,
    VendorCatalogProductDetailView,
    VendorCatalogProposalListCreateView,
    VendorCreateProductFromCatalogView,
    VendorInheritedProductDetailView,
    VendorInheritedProductDraftBatchCreateView,
    VendorInheritedProductDuplicateView,
    VendorInheritedProductImagePolicyView,
    VendorInheritedProductListView,
    VendorInheritedProductSubmitView,
)
from .wishlist_views import WishlistView, WishlistToggleView, WishlistStatusView

__all__ = [
    'CategoryListView',
    'ProductListView',
    'FeaturedProductsView',
    'ProductDetailView',
    'VendorProductImagesView',
    'VendorProductImageDetailView',
    'VendorStockUpdateView',
    'VendorLowStockView',
    'AIImageGenerateView',
    'ProductReviewViewSet',
    'AdminCategoryListCreateView',
    'AdminCategoryDetailView',
    'AdminProductListCreateView',
    'AdminProductDetailView',
    'AdminCatalogProductDetailView',
    'AdminCatalogProductImageDetailView',
    'AdminCatalogProductImagesView',
    'AdminCatalogProductGrantVendorView',
    'AdminCatalogProductListCreateView',
    'AdminCatalogProposalItemApproveView',
    'AdminCatalogProposalItemRejectView',
    'AdminCatalogProposalListView',
    'AdminApproveVendorProductView',
    'AdminPendingVendorProductListView',
    'AdminRejectVendorProductView',
    'VendorAvailableCatalogProductsView',
    'VendorCatalogProductDetailView',
    'VendorCatalogProposalListCreateView',
    'VendorCreateProductFromCatalogView',
    'VendorInheritedProductDetailView',
    'VendorInheritedProductDraftBatchCreateView',
    'VendorInheritedProductDuplicateView',
    'VendorInheritedProductImagePolicyView',
    'VendorInheritedProductListView',
    'VendorInheritedProductSubmitView',
    'WishlistView',
    'WishlistToggleView',
    'WishlistStatusView',
]
