# Generated by Django 4.2.29 on 2026-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadedfile_use_of_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='use_of_image',
            field=models.CharField(choices=[('profile_image', 'Profile image'), ('cover_image', 'Cover image'), ('product_image', 'Product image'), ('category_image', 'Category image'), ('vendor_document', 'Vendor document'), ('delivery_document', 'Delivery document'), ('order_attachment', 'Order attachment'), ('delivery_proof', 'Delivery proof'), ('transaction_proof', 'Transaction proof'), ('invoice', 'Invoice'), ('banner_image', 'Banner image'), ('general_upload', 'General upload')], default='general_upload', max_length=40),
        ),
    ]
