# Generated by Django 4.2.29 on 2026-05-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_uploadedfile_use_of_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='client_upload_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
