# Generated by Django 4.2.29 on 2026-03-23 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='auto_order_acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='cancellation_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='dispatch_sla_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fulfillment_type',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor Fulfilled'), ('platform', 'Platform Fulfilled')], default='vendor', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='packaging_preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='return_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('company', 'Company'), ('partnership', 'Partnership')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='VendorOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('vendor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('partnership', 'Partnership')], default='individual', max_length=20)),
                ('contact_person_name', models.CharField(blank=True, max_length=200)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254)),
                ('contact_person_phone', models.CharField(blank=True, max_length=15)),
                ('gst_registered', models.BooleanField(default=False)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('cin_udyam', models.CharField(blank=True, help_text='CIN or Udyam Registration number', max_length=50)),
                ('fssai_license', models.CharField(blank=True, max_length=50)),
                ('trademark_number', models.CharField(blank=True, max_length=50)),
                ('business_addresses', models.JSONField(blank=True, default=list)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('onboarding_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboardings', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('pan_card', 'PAN Card'), ('gstin_certificate', 'GSTIN Certificate'), ('identity_proof', 'Identity Proof (Aadhaar / Passport)'), ('address_proof', 'Address Proof'), ('cancelled_cheque', 'Cancelled Cheque'), ('fssai_license', 'FSSAI License'), ('trademark', 'Trademark Certificate'), ('business_registration', 'Business Registration (CIN / Udyam)')], max_length=30)),
                ('file', models.FileField(upload_to='vendor_documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBankDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('account_number_enc', models.TextField(blank=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(blank=True, choices=[('savings', 'Savings'), ('current', 'Current')], default='current', max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('settlement_cycle', models.CharField(blank=True, choices=[('T+1', 'Next Day (T+1)'), ('T+7', 'Weekly (T+7)'), ('T+15', 'Fortnightly (T+15)'), ('T+30', 'Monthly (T+30)')], default='T+7', max_length=5)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Vendor Created'), ('profile_updated', 'Profile Updated'), ('status_changed', 'Status Changed'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('bank_updated', 'Bank Details Updated'), ('bank_verified', 'Bank Details Verified'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('onboarding_submitted', 'Onboarding Submitted'), ('onboarding_approved', 'Onboarding Approved'), ('onboarding_rejected', 'Onboarding Rejected'), ('serviceable_area_added', 'Serviceable Area Added'), ('holiday_added', 'Holiday Added')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorServiceableArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceable_areas', to='vendors.vendor')),
            ],
            options={
                'ordering': ['pincode'],
                'unique_together': {('vendor', 'pincode')},
            },
        ),
        migrations.CreateModel(
            name='VendorHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='vendors.vendor')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('vendor', 'date')},
            },
        ),
    ]
