# Generated by Django 4.2.29 on 2026-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_rename_pending_verify_to_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
