# Generated by Django 4.2.29 on 2026-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendorwallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='base_prep_time_min',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_time_per_km_min',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='vendor',
            name='instant_delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='max_delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendor',
            name='scheduled_buffer_min',
            field=models.IntegerField(default=30),
        ),
    ]
