# Generated by Django 4.2.29 on 2026-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_add_delivery_quote_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
    ]
