# Generated by Django 4.2.29 on 2026-05-24 16:00

from django.db import migrations, models
import helpers.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_vendor_store_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('cover_image')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('profile_image')),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='file',
            field=models.FileField(upload_to=helpers.upload_paths.UserDateUploadPath('vendor_document')),
        ),
    ]
