# Generated by Django 4.2.29 on 2026-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_vendor_banner_alter_vendor_logo_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status', 'is_accepting_orders', 'city', 'state'], name='vendor_public_area_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status', 'is_open', 'is_accepting_orders'], name='vendor_open_status_idx'),
        ),
    ]
