# Generated by Codex on 2026-06-03

from django.db import migrations, models
import helpers.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_vendor_vendor_public_area_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordocument',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('license', 'Business / Trade License'),
                    ('pan_card', 'PAN Card'),
                    ('gstin_certificate', 'GSTIN Certificate'),
                    ('identity_proof', 'Identity Proof (Aadhaar / Passport)'),
                    ('address_proof', 'Address Proof'),
                    ('cancelled_cheque', 'Cancelled Cheque'),
                    ('fssai_license', 'FSSAI License'),
                    ('trademark', 'Trademark Certificate'),
                    ('business_registration', 'Business Registration (CIN / Udyam)'),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='file',
            field=models.FileField(upload_to=helpers.upload_paths.VendorDocumentUploadPath()),
        ),
    ]
