# Generated by Django 4.2.29 on 2026-10-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_fulfillment_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordocument',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
