# Generated by Django 4.2.29 on 2026-04-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_payment_method_otp_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
