# Generated by Django 4.2.29 on 2026-04-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendor_wallet_balance'),
        ('orders', '0006_orderissue_issuemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendors.deliverypartnerpayout'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vendors.vendorpayout'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, help_text='Max uses per customer'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True),
        ),
    ]
