# Generated by Django 4.2.29 on 2026-04-16 07:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_razorpay_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='cancellation_allowed_statuses',
            field=models.JSONField(default=list, help_text='Statuses from which cancellation is allowed, e.g. ["placed","confirmed"].'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='cancellation_window_minutes',
            field=models.IntegerField(default=10, help_text='Minutes after placement within which customer can cancel. 0 = always allowed.'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='delivery_base_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Base delivery fee in ₹ regardless of distance.', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='delivery_per_km_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Additional ₹ charged per km of distance.', max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='free_delivery_above',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Orders with subtotal above this amount get free delivery. Set 0 to disable.', max_digits=10),
        ),
    ]
