# Generated by Django 4.2.29 on 2026-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_platformsetting_rate_card_and_cancellation_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('initiated', 'Refund Initiated'), ('processed', 'Refund Processed'), ('failed', 'Refund Failed')], default='none', max_length=20),
        ),
    ]
