# Generated by Django 4.2.29 on 2026-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_deliveryzone_center_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderissue',
            name='issue_type',
            field=models.CharField(choices=[('return', 'Return Request'), ('refund', 'Refund Request'), ('damage', 'Damaged Item'), ('mismatch', 'Item Mismatch'), ('late', 'Late Delivery')], max_length=20),
        ),
    ]
