# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderissue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Optional hex color for customer app offer cards', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='badge_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='coupon',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='display_section',
            field=models.CharField(choices=[('hero', 'Featured'), ('more', 'More offers')], default='more', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Material icon name used by customer apps', max_length=60),
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['display_order', '-created_at']},
        ),
    ]
