# Generated by Django 4.2.29 on 2026-05-24 16:00

from django.db import migrations, models
import helpers.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_checkout_price_breakup_and_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('delivery_proof')),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_photo',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('transaction_proof')),
        ),
        migrations.AlterField(
            model_name='orderissueattachment',
            name='file',
            field=models.FileField(upload_to=helpers.upload_paths.UserDateUploadPath('order_attachment')),
        ),
        migrations.AlterField(
            model_name='platformbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('banner_image')),
        ),
    ]
