# Generated by Django 4.2.29 on 2026-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_paymentsession'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active', 'valid_from', 'valid_until'], name='coupon_code_active_valid_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['vendor', 'is_active', 'valid_from'], name='coupon_vendor_active_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user', '-used_at'], name='coupon_usage_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status', '-placed_at'], name='ord_cust_status_placed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor', 'status', '-placed_at'], name='ord_vendor_status_pl_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_partner', 'status'], name='ord_delivery_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-placed_at'], name='ord_status_placed_idx'),
        ),
    ]
