# Generated by Django 4.2.29 on 2026-10-01 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0034_customerrecommendationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='queue',
            field=models.CharField(blank=True, default='support', max_length=60),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('refund', 'Refund review'), ('replacement', 'Replacement review'), ('compensation', 'Compensation review'), ('explanation', 'Explanation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderissue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('refund_initiated', 'Refund Initiated'), ('assigned', 'Assigned'), ('investigating', 'Investigating'), ('waiting_customer', 'Waiting for customer'), ('waiting_vendor', 'Waiting for vendor'), ('waiting_partner', 'Waiting for partner'), ('resolution_pending', 'Resolution pending'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='open', max_length=20),
        ),
    ]
