from django.db import migrations

REGISTERED_APPLICATIONS = [{'id': 'vendor-app',
  'name': 'Vendor App',
  'description': 'Registered routes with availability guards. Authentication remains enforced independently.',
  'icon': 'storefront',
  'color': 'green',
  'pages': [{'id': 'vendor-live-orders',
             'appId': 'vendor-app',
             'name': 'Live Orders',
             'description': 'Availability for this registered application route.',
             'route': '/live-orders',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-inventory',
             'appId': 'vendor-app',
             'name': 'Inventory',
             'description': 'Availability for this registered application route.',
             'route': '/inventory',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-products',
             'appId': 'vendor-app',
             'name': 'Products',
             'description': 'Availability for this registered application route.',
             'route': '/products',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-product-new',
             'appId': 'vendor-app',
             'name': 'Products New',
             'description': 'Availability for this registered application route.',
             'route': '/products/new',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-product-edit',
             'appId': 'vendor-app',
             'name': 'Products Edit',
             'description': 'Availability for this registered application route.',
             'route': '/products/:id/edit',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-product-edit',
             'appId': 'vendor-app',
             'name': 'Products Edit',
             'description': 'Availability for this registered application route.',
             'route': '/products/edit/:id',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-catalog-requests',
             'appId': 'vendor-app',
             'name': 'Catalog Requests',
             'description': 'Availability for this registered application route.',
             'route': '/catalog-requests',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-orders',
             'appId': 'vendor-app',
             'name': 'Orders',
             'description': 'Availability for this registered application route.',
             'route': '/orders',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-order-prep',
             'appId': 'vendor-app',
             'name': 'Orders Prep',
             'description': 'Availability for this registered application route.',
             'route': '/orders/:id/prep',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-order-detail',
             'appId': 'vendor-app',
             'name': 'Orders',
             'description': 'Availability for this registered application route.',
             'route': '/orders/:id',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-analytics',
             'appId': 'vendor-app',
             'name': 'Analytics',
             'description': 'Availability for this registered application route.',
             'route': '/analytics',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-payouts',
             'appId': 'vendor-app',
             'name': 'Payouts',
             'description': 'Availability for this registered application route.',
             'route': '/payouts',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-promotions',
             'appId': 'vendor-app',
             'name': 'Promotions',
             'description': 'Availability for this registered application route.',
             'route': '/promotions',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-support',
             'appId': 'vendor-app',
             'name': 'Support',
             'description': 'Availability for this registered application route.',
             'route': '/support',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-reviews',
             'appId': 'vendor-app',
             'name': 'Reviews',
             'description': 'Availability for this registered application route.',
             'route': '/reviews',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-notifications',
             'appId': 'vendor-app',
             'name': 'Notifications',
             'description': 'Availability for this registered application route.',
             'route': '/notifications',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-store-settings',
             'appId': 'vendor-app',
             'name': 'Store Settings',
             'description': 'Availability for this registered application route.',
             'route': '/store/settings',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'vendor-store-settings',
             'appId': 'vendor-app',
             'name': 'Store Settings',
             'description': 'Availability for this registered application route.',
             'route': '/store-settings',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []}]},
 {'id': 'delivery-app',
  'name': 'Delivery App',
  'description': 'Registered routes with availability guards. Authentication remains enforced independently.',
  'icon': 'two_wheeler',
  'color': 'blue',
  'pages': [{'id': 'delivery-available',
             'appId': 'delivery-app',
             'name': 'Available',
             'description': 'Availability for this registered application route.',
             'route': '/available',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'delivery-active',
             'appId': 'delivery-app',
             'name': 'Active',
             'description': 'Availability for this registered application route.',
             'route': '/active',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'delivery-history',
             'appId': 'delivery-app',
             'name': 'History',
             'description': 'Availability for this registered application route.',
             'route': '/history',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'delivery-earnings',
             'appId': 'delivery-app',
             'name': 'Earnings',
             'description': 'Availability for this registered application route.',
             'route': '/earnings',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'delivery-profile',
             'appId': 'delivery-app',
             'name': 'Profile',
             'description': 'Availability for this registered application route.',
             'route': '/profile',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []}]},
 {'id': 'customer-app',
  'name': 'Customer App',
  'description': 'Registered routes with availability guards. Authentication remains enforced independently.',
  'icon': 'shopping_bag',
  'color': 'orange',
  'pages': [{'id': 'customer-home',
             'appId': 'customer-app',
             'name': 'Home',
             'description': 'Availability for this registered application route.',
             'route': '/',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-categories',
             'appId': 'customer-app',
             'name': 'Categories',
             'description': 'Availability for this registered application route.',
             'route': '/categories',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-explore',
             'appId': 'customer-app',
             'name': 'Explore',
             'description': 'Availability for this registered application route.',
             'route': '/explore',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-explore-categoryId',
             'appId': 'customer-app',
             'name': 'Explore :categoryid',
             'description': 'Availability for this registered application route.',
             'route': '/explore/:categoryId',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-stores',
             'appId': 'customer-app',
             'name': 'Stores',
             'description': 'Availability for this registered application route.',
             'route': '/stores',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-category-id',
             'appId': 'customer-app',
             'name': 'Category',
             'description': 'Availability for this registered application route.',
             'route': '/category/:id',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-store-id',
             'appId': 'customer-app',
             'name': 'Store',
             'description': 'Availability for this registered application route.',
             'route': '/store/:id',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-product-id',
             'appId': 'customer-app',
             'name': 'Product',
             'description': 'Availability for this registered application route.',
             'route': '/product/:id',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-cart',
             'appId': 'customer-app',
             'name': 'Cart',
             'description': 'Availability for this registered application route.',
             'route': '/cart',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-checkout',
             'appId': 'customer-app',
             'name': 'Checkout',
             'description': 'Availability for this registered application route.',
             'route': '/checkout',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-orders',
             'appId': 'customer-app',
             'name': 'Orders',
             'description': 'Availability for this registered application route.',
             'route': '/orders',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-order-confirmed-id',
             'appId': 'customer-app',
             'name': 'Order Confirmed',
             'description': 'Availability for this registered application route.',
             'route': '/order-confirmed/:id',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-tracking-id',
             'appId': 'customer-app',
             'name': 'Tracking',
             'description': 'Availability for this registered application route.',
             'route': '/tracking/:id',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-order-finished-id',
             'appId': 'customer-app',
             'name': 'Order Finished',
             'description': 'Availability for this registered application route.',
             'route': '/order-finished/:id',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-order-id-rating',
             'appId': 'customer-app',
             'name': 'Order Rating',
             'description': 'Availability for this registered application route.',
             'route': '/order/:id/rating',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-account',
             'appId': 'customer-app',
             'name': 'Account',
             'description': 'Availability for this registered application route.',
             'route': '/account',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-addresses',
             'appId': 'customer-app',
             'name': 'Addresses',
             'description': 'Availability for this registered application route.',
             'route': '/addresses',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-notifications',
             'appId': 'customer-app',
             'name': 'Notifications',
             'description': 'Availability for this registered application route.',
             'route': '/notifications',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []},
            {'id': 'customer-privacy-policy',
             'appId': 'customer-app',
             'name': 'Privacy Policy',
             'description': 'Availability for this registered application route.',
             'route': '/privacy-policy',
             'status': 'enabled',
             'protected': True,
             'lastUpdated': 'Registered route',
             'features': []}]}]


def seed(apps, schema_editor):
    flags = apps.get_model('orders', 'FeatureFlag')
    flag, created = flags.objects.get_or_create(key='page_feature_management', defaults={'name':'Page & Feature Management','is_enabled':True,'audience':'all','rollout_percentage':100,'metadata':{}})
    metadata = flag.metadata if isinstance(flag.metadata, dict) else {}
    if not metadata.get('applications'):
        metadata['applications'] = REGISTERED_APPLICATIONS
        metadata.setdefault('version',1)
        flag.metadata=metadata
        flag.save(update_fields=['metadata'])


class Migration(migrations.Migration):
    dependencies=[('orders','0035_order_dispatch_escalated_at_order_dispatch_notes_and_more')]
    operations=[migrations.RunPython(seed,migrations.RunPython.noop)]
