# Generated by Django 4.2.29 on 2026-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('delivery', 'Delivery Update'), ('payout', 'Payout Update'), ('promo', 'Promotion'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
