# Generated by Django 4.2.29 on 2026-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
