# Generated by Django 4.2.29 on 2026-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('sold_out', 'Sold Out'), ('coming_soon', 'Coming Soon'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
