# Generated by Django 4.2.29 on 2026-04-29 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.utils.text import slugify


def migrate_existing_products_to_catalog(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    CatalogProduct = apps.get_model('products', 'CatalogProduct')
    VendorCatalogGrant = apps.get_model('products', 'VendorCatalogGrant')

    catalog_by_key = {}
    used_slugs = set(CatalogProduct.objects.values_list('slug', flat=True))

    def unique_slug(name):
        base = slugify(name) or 'catalog-product'
        candidate = base
        n = 1
        while candidate in used_slugs or CatalogProduct.objects.filter(slug=candidate).exists():
            candidate = f'{base}-{n}'
            n += 1
        used_slugs.add(candidate)
        return candidate

    products = Product.objects.select_related('category', 'vendor').all().order_by('created_at')
    for product in products:
        key = (
            (product.name or '').strip().lower(),
            str(product.category_id or ''),
            (product.brand or '').strip().lower(),
        )
        catalog_product = catalog_by_key.get(key)
        if not catalog_product:
            catalog_product = CatalogProduct.objects.create(
                category_id=product.category_id,
                name=product.name,
                slug=unique_slug(product.name),
                description=product.description,
                brand=product.brand,
                unit=product.unit,
                barcode=product.barcode,
                search_keywords=product.search_keywords,
                compliance_notes=product.compliance_notes,
                is_active=True,
            )
            catalog_by_key[key] = catalog_product
        product.catalog_product_id = catalog_product.id
        product.save(update_fields=['catalog_product'])
        VendorCatalogGrant.objects.get_or_create(
            vendor_id=product.vendor_id,
            catalog_product_id=catalog_product.id,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0009_add_delivery_quote_fields'),
        ('products', '0006_product_vendor_operational_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(default='piece', max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('search_keywords', models.CharField(blank=True, max_length=255)),
                ('compliance_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_approved', 'Partially Approved'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=24)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_catalog_proposals', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_proposals', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProposalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(default='piece', max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('sku_hint', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('created_catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_items', to='products.catalogproduct')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.catalogproposal')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='catalog-products/')),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('catalog_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.catalogproduct')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_products', to='products.catalogproduct'),
        ),
        migrations.CreateModel(
            name='VendorCatalogGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_grants', to='products.catalogproduct')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_grants_made', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_grants', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('vendor', 'catalog_product')},
            },
        ),
        migrations.RunPython(migrate_existing_products_to_catalog, noop_reverse),
    ]
