# Generated by Django 4.2.29 on 2026-05-24 16:00

from django.db import migrations, models
import helpers.upload_paths


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_update_category_icon_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproductimage',
            name='image',
            field=models.ImageField(upload_to=helpers.upload_paths.UserDateUploadPath('product_image')),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_paths.UserDateUploadPath('category_image')),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=helpers.upload_paths.UserDateUploadPath('product_image')),
        ),
    ]
