# Generated by Django 4.2.29 on 2026-05-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_catalogproductimage_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'status', 'approval_status', 'is_available', 'stock'], name='prod_vendor_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', 'approval_status'], name='prod_category_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'approval_status', 'is_available', 'stock'], name='prod_public_visible_idx'),
        ),
    ]
