# Generated by Django 4.2.29 on 2026-10-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_prod_vendor_visible_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval_note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
